<?php

/**
 * @file
 * Contains time_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function time_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the time_field module.
    case 'help.page.time_field':
      $output = '';
      $output .= '<h3>' . t('What "Time field" module provides?') . '</h3>';
      $output .= '<p>' . t('This module provides Time and TimeRange fields also corresponding widgets and formatters.') . '</p>';
      $output .= '<h3>' . t('How it saves data?') . '</h3>';
      $output .= '<p>' . t('Time field module saves time data as integers number of seconds passed through midnight.') . '</p>';
      return $output;

    default:
  }
}
