<?php

use Drupal\taxonomy\Entity\Term;
use Drupal\block\Entity\Block;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_preprocess_breadcrumb()
 */
function link_core_preprocess_breadcrumb(&$variables) {
	// override breadcrumb if a query parameter is set
  $service_tid = \Drupal::request()->query->get('svtid');
  if (!empty($service_tid)) {
  	// get taxonomy term url
  	$term = Term::load($service_tid);
  	if (is_object($term)) {
  		$name = $term->getName();
			$url = $term->toUrl()->toString();
			// get current title
			$route = \Drupal::routeMatch()->getCurrentRouteMatch()->getRouteObject();
			$title = $route->getDefault('_title');
			// set breadcrumb
			$breadcrumb = [
				[
					'text' => $name,
					'url' => $url,
				],
			];
			$variables['breadcrumb'] = $breadcrumb;
  	}
  }
  // set breadcrumbs to cache based on URL
  $variables['#cache']['contexts'][] = 'url.path';
}

function link_core_block_access(Block $block, $operation, AccountInterface $account) {
	if ($block->id() === 'views_block__locations_on_user_block_1' ||
		$block->id() === 'views_block__user_details_block_1' ||
		$block->id() === 'views_block__locations_on_user_block_2') {
		$current_path = \Drupal::service('path.current')->getPath();
		$path_items = explode('/', $current_path);
		if (is_array($path_items) &&
		count($path_items) == 3 &&
		isset($path_items[1]) &&
		$path_items[1] === 'user' &&
		isset($path_items[2]) &&
		is_integer((int) $path_items[2])) {
			if ($block->id() === 'views_block__locations_on_user_block_1') {
				// if the user is authenticated && (it’s his profile or he’s an admin)
				if (!\Drupal::currentUser()->isAnonymous() &&
				(\Drupal::currentUser()->id() == (int) $path_items[2] ||
				\Drupal::currentUser()->id() == 1) ||
				in_array('prm_administrator', \Drupal::currentUser()->getRoles())
				) {
					return AccessResult::allowed();
				}
				return AccessResult::forbidden();
			}
			if ($block->id() === 'views_block__locations_on_user_block_2') {
				// if the user is not authenticated OR it's someone else's profile & it's not an admin
				if (\Drupal::currentUser()->isAnonymous() ||
				(\Drupal::currentUser()->id() != (int) $path_items[2] &&
				\Drupal::currentUser()->id() != 1) &&
				!in_array('prm_administrator', \Drupal::currentUser()->getRoles())) {
					return AccessResult::allowed();
				}
				return AccessResult::forbidden();
			}
		return AccessResult::neutral();
	}
	return AccessResult::forbidden();
	}
	if ($block->id() === 'link2_views_block__service_block_1' ||
		$block->id() === 'link2_views_block__service_block_2') {
			$current_path = \Drupal::service('path.current')->getPath();
			$path_items = explode('/', $current_path);
			if (count($path_items) === 3) {
				return AccessResult::neutral();
			}
			else {
				return AccessResult::forbidden();
			}
	}
}