definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    weight: -45
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  user__page:
    weight: -50
    parent: 'menu_link_content:427dcf84-dc4b-42ed-8301-ecbb3274af55'
    menu_name: account
    enabled: true
    expanded: false
  user__logout:
    weight: -49
    parent: 'menu_link_content:427dcf84-dc4b-42ed-8301-ecbb3274af55'
    menu_name: account
    expanded: false
    enabled: true
  comment__admin:
    weight: -60
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
