definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    weight: -45
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  user__page:
    enabled: true
    menu_name: account
    parent: ''
    expanded: false
    weight: -10
  user__logout:
    enabled: true
    menu_name: account
    parent: ''
    weight: 10
    expanded: false
  comment__admin:
    weight: -60
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
