<?php

/**
 * @file
 * Add bookmarking abilities to AJAX Views.
 */

use \Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function views_ajax_history_views_pre_render(ViewExecutable $view) {
  if ($view->ajaxEnabled() && empty($view->is_attachment) && empty($view->live_preview)) {
    // @TODO add option to views form for html4+html5 or html5 only
    $view->element['#attached']['library'][] = 'views_ajax_history/history';
    $view->element['#attached']['drupalSettings']['viewsAjaxHistory'] = ['renderPageItem' => pager_find_page()];
    $view->element['#cache']['contexts'][] = 'url.query_args.pagers';
  }
}
